# Basic Information 
title: Zijian Cao
position: Ph.D. Student in Computer Science
affiliation: The University of Texas at Austin
affiliation_link: https://www.utexas.edu/
affiliation_logo: /assets/img/Texas-Longhorns-01.png
email: zccao@cs.utexas.edu

# Search Engine Optimization (SEO)
keywords: zijian cao, cao zijian, mobile computing, mobile AI, wearable computing, visual computing
url: https://zjcharlescao.github.io
baseurl: /zccao
canonical: https://zjcharlescao.github.io/zccao
description: A Ph.D. student in Computer Science at The University of Texas at Austin researching mobile computing, artificial intelligence, and visual computing.

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=b58f2XIAAAAJ&hl=en
github_link: https://github.com/ZJCharlesCao/
linkedin: https://www.linkedin.com/in/zijian-cao-1537152a5/

# Images 
avatar: /assets/img/zijian.jpg

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: HV0rAUdAxpfEQLOsVs0FcJTR2rKVI5sEQUZIDM-N_HY

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - html_source_file
  - bio.md
